### ISSUE TITLE
Installation not reproducible

### ISSUE THREAD

**Issue by adthoms** [MarineRoboticsGroup/PyFactorGraph#1]
Following the installation guide (with the exception of using `pip3` instead of `pip`), the following errors are produced when executing [efg_data.py](https://github.com/MarineRoboticsGroup/PyFactorGraph/blob/main/examples/efg_data.py) and [pickle_data.py](https://github.com/MarineRoboticsGroup/PyFactorGraph/blob/main/examples/pickle_data.py), respectively:
```
~$ python3 ~/PyFactorGraph/examples/efg_data.py
Traceback (most recent call last):
  File "/home/alex/catkin_ws/src/py_sandbox/examples/pickle_data.py", line 24, in <module>
    main()
  File "/home/alex/catkin_ws/src/py_sandbox/examples/pickle_data.py", line 16, in main
    factor_graph = parse_pickle_file(data_file)
  File "/home/alex/PyFactorGraph/py_factor_graph/parsing/parse_pickle_file.py", line 31, in parse_pickle_file
    data = pickle.load(f)
ModuleNotFoundError: No module named 'factor_graph'
```
```
~$ python3 ~/PyFactorGraph/examples/pickle_data.py
Traceback (most recent call last):
  File "/home/alex/catkin_ws/src/py_sandbox/examples/efg_data.py", line 24, in <module>
    main()
  File "/home/alex/catkin_ws/src/py_sandbox/examples/efg_data.py", line 16, in main
    factor_graph = parse_efg_file(data_file)
  File "/home/alex/PyFactorGraph/py_factor_graph/parsing/parse_efg_file.py", line 117, in parse_efg_file
    new_fg_data.add_odom_measurement(base_pose_idx, measure)
  File "/home/alex/PyFactorGraph/py_factor_graph/factor_graph.py", line 767, in add_odom_measurement
    assert self.pose_exists(to_pose)
AssertionError
```
Note that the first line of [factor_graph.fg](https://github.com/MarineRoboticsGroup/PyFactorGraph/blob/main/examples/data/factor_graph.fg) was modified to: 
```
Variable Pose SE2 A0 0.000000000000000 0.000000000000000 0.000000000000000
```

To reproduce the second error, while leaving the file unmodified results in the following third error:
```
~$ python3 ~/PyFactorGraph/examples/efg_data.py
Traceback (most recent call last):
  File "/home/alex/PyFactorGraph/examples/efg_data.py", line 24, in <module>
    main()
  File "/home/alex/PyFactorGraph/examples/efg_data.py", line 16, in main
    factor_graph = parse_efg_file(data_file)
  File "/home/alex/.local/lib/python3.6/site-packages/py_factor_graph/parsing/parse_efg_file.py", line 68, in parse_efg_file
    pose_var = PoseVariable2D(pose_name, (x, y), theta)
  File "<attrs generated init py_factor_graph.variables.PoseVariable2D>", line 9, in __init__
  File "/home/alex/.local/lib/python3.6/site-packages/py_factor_graph/utils/attrib_utils.py", line 220, in variable_name_validator
    raise ValueError(f"{value} does not end with a number")
ValueError: A does not end with a number
```

Both the first and second errors lead me to believe there is an issue with the current installation. The installation has been tested in a clean [virtual environment](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/) with the following libraries: matplotlib, evo, coloredlogs, setuptools. The version of Python3 used is 3.6.9.

**Comment by adthoms** [comment]
@alanpapalia have you encountered these errors before? I am currently working through this issue.

**Comment by alanpapalia** [comment]
Ahh good catch. I think I may have modified the library and not ensured
that some of the parser functionality was maintained.

I'll try to look at that soon and see what's going on, but I think that it
should be fine even if the examples aren't working.

**Comment by alanpapalia** [comment]
Looked at it - I think a few things happened
1) the EFG data file looked like it was broken/modified to be incorrect somehow
2) because `.pickle` files package up the environments that are being used, substantial API changes broke the example. It could be done with a fresh `.pickle` file (this is how I normally pass these PyFG objects around) but is probably a pain while this library is still receiving regular updates

Proposed solution: remove the examples entirely for now. When we integrate other, more useful parsers, for text-based formats (e.g., g2o) then we can write some new examples

Opening a new PR for this

**Comment by alanpapalia** [comment]
@adthoms let me know what you think

**Comment by adthoms** [comment]
@alanpapalia This makes sense, Thanks! I can take on integrating g2o parsing from pyfg-utilities with unit testing.
